' Gambas module file

Public Sub LightMode()
  'Plasma Global Theme set
  Shell "lookandfeeltool -a xyz.pearos.alxb421.pearOS" Wait
  
  'Plasma color-scheme set
  Shell "plasma-apply-colorscheme pearOS" Wait
  
  'latte-dock set
  Shell "cp /usr/share/extras/drawing-black.svg /usr/share/extras/pearlogo.svg" Wait
  Shell "cp /usr/share/extras/sideBar-controlCentre-original.svg /usr/share/extras/sidebar.svg" Wait
  Shell "killall latte-dock && latte-dock & disown"
  
  'Kantum theme set
  Shell "kvantummanager --set pearOS" Wait 
  
  'GTK set
  Shell "echo ' ' > ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo '[Settings]' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-application-prefer-dark-theme=false\n' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-button-images=true' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-cursor-theme-name=WhiteSur-cursors' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-cursor-theme-size=24' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-decoration-layout=close,minimize,maximize:' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-enable-animations=true' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-font-name=Noto Sans,  10' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-icon-theme-name=pearOS' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-menu-images=true' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-modules=colorreload-gtk-module:window-decorations-gtk-module:appmenu-gtk-module' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-primary-button-warps-slider=false' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-shell-shows-menubar=1' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-theme-name=pearOS' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-toolbar-style=3' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  
  'Config File for the app itself. If active.dark is present means that the active theme is dark; If active.light is present, means that the active theme is light
  Shell "rm -Rf /usr/share/extras/active.* && touch /usr/share/extras/active.light"
End


Public Sub DarkMode()
  'Plasma Global Theme set
  Shell "lookandfeeltool -a xyz.pearos.alxb421.pearOS-dark" Wait
  
  'Plasma color-scheme set
  Shell "plasma-apply-colorscheme pearOS-dark" Wait
  
  'latte-dock set
  Shell "cp /usr/share/extras/drawing.svg /usr/share/extras/pearlogo.svg"
  Shell "cp /usr/share/extras/sideBar-controlCentre-white.svg /usr/share/extras/sidebar.svg"
  Shell "killall latte-dock && latte-dock & disown"
  
  'Kantum theme set
  Shell "kvantummanager --set pearOS-dark" Wait 
  
  'GTK set
  Shell "echo ' ' > ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo '[Settings]' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-application-prefer-dark-theme=false\n' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-button-images=true' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-cursor-theme-name=WhiteSur-cursors' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-cursor-theme-size=24' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-decoration-layout=close,minimize,maximize:' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-enable-animations=true' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-font-name=Noto Sans,  10' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-icon-theme-name=pearOS-dark' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-menu-images=true' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-modules=colorreload-gtk-module:window-decorations-gtk-module:appmenu-gtk-module' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-primary-button-warps-slider=false' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-shell-shows-menubar=1' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-theme-name=pearOS-dark' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-toolbar-style=3' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  
  'Config File for the app itself. If active.dark is present means that the active theme is dark; If active.light is present, means that the active theme is light
  Shell "rm -Rf /usr/share/extras/active.* && touch /usr/share/extras/active.dark"
End
