' Gambas module file

Public Sub light()
  
  Shell "echo ' ' > ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo '[Settings]' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-application-prefer-dark-theme=false\n' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-button-images=true' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-cursor-theme-name=WhiteSur-cursors' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-cursor-theme-size=24' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-decoration-layout=close,minimize,maximize:' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-enable-animations=true' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-font-name=Noto Sans,  10' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-icon-theme-name=WhiteSur' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-menu-images=true' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-modules=colorreload-gtk-module:window-decorations-gtk-module:appmenu-gtk-module' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-primary-button-warps-slider=false' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-shell-shows-menubar=1' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-theme-name=pearOS' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-toolbar-style=3' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  
End



Public Sub dark()
  
  Shell "echo ' ' > ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo '[Settings]' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-application-prefer-dark-theme=false\n' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-button-images=true' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-cursor-theme-name=WhiteSur-cursors' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-cursor-theme-size=24' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-decoration-layout=close,minimize,maximize:' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-enable-animations=true' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-font-name=Noto Sans,  10' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-icon-theme-name=WhiteSur' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-menu-images=true' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-modules=colorreload-gtk-module:window-decorations-gtk-module:appmenu-gtk-module' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-primary-button-warps-slider=false' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-shell-shows-menubar=1' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-theme-name=pearOS-dark' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  Shell "echo 'gtk-toolbar-style=3' | tee -a ~/.config/gtk-3.0/settings.ini" Wait
  
End
